# cron job to keep render api warm, runs every 14 min

name: Fake Traffic

on:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s https://portfolio-website-backend-pmak.onrender.com/ping